[package]
name = "siderust-pod-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for Siderust POD."

[[bin]]
name = "siderust-pod"
path = "src/main.rs"

[dependencies]
siderust-pod-service.workspace = true
clap.workspace = true
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true

[lints]
workspace = true
